kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: kadalu-csi-nodeplugin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: csi-driver
spec:
  selector:
    matchLabels: {{- include "common.labels.standard" . | nindent 6 }}
      app.kubernetes.io/component: csi-driver
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: csi-driver
      namespace: {{ .Release.Namespace }}
    spec:
      serviceAccountName: kadalu-csi-nodeplugin
      containers:
        - name: csi-node-driver-registrar
          image: dockerhub.cisco.com/robot-dockerprod/csi-node-driver-registrar:v2.8.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/kadalu /registration/kadalu-reg.sock"]
          livenessProbe:
            exec:
              command:
              - /csi-node-driver-registrar
              - --kubelet-registration-path={{ include "common.configs.kubeletDir" . }}/plugins/kadalu/csi.sock
              - --mode=kubelet-registration-probe
            initialDelaySeconds: 5
            timeoutSeconds: 15
          env:
            - name: ADDRESS
              value: /plugin/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ include "common.configs.kubeletDir" . }}/plugins/kadalu/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: kadalu-nodeplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: dockerhub.cisco.com/robot-dockerprod/kadalu-csi-driver:2.0.8
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
            - name: KADALU_VERSION
              value: {{ include "common.version" . | quote }}
            - name: K8S_DIST
              value: {{ .Values.global.kubernetesDistro | quote }}
            - name: VERBOSE
              value: {{ .Values.verbose | quote }}
            - name: CSI_ROLE
              value: "nodeplugin"
            - name: CREATE_MOUNT_ON_VMEXEC
              value: "True"
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: {{ include "common.configs.kubeletDir" . }}/pods
              mountPropagation: "Bidirectional"
            - name: glusterfsd-volfilesdir
              mountPath: "/var/lib/gluster"
            - name: gluster-dev
              mountPath: "/dev"
            - name: varlog
              mountPath: /var/log/gluster
            - name: csi-dir
              mountPath: {{ include "common.configs.kubeletDir" . }}/plugins/kubernetes.io/csi
              mountPropagation: "Bidirectional"
            - name: kadalu-storagevol
              mountPath: /mnt/
            - name: glusterfs-vol
              mountPath: /var/run/vmexec-socket/
        - name: kadalu-logging
          image: docker.io/library/busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do logcnt=$(/bin/ls /var/log/gluster/ | wc -l); if [ ${logcnt} -gt 0 ]; then break; fi; sleep 5; done; tail -F /var/log/gluster/*.log"]
          volumeMounts:
            - name: varlog
              mountPath: "/var/log/gluster"
      volumes:
        - name: plugin-dir
          hostPath:
            path: {{ include "common.configs.kubeletDir" . }}/plugins/kadalu
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: {{ include "common.configs.kubeletDir" . }}/pods
            type: Directory
        - name: registration-dir
          hostPath:
            path: {{ include "common.configs.kubeletDir" . }}/plugins_registry/
            type: Directory
        - name: glusterfsd-volfilesdir
          configMap:
            name: "kadalu-info"
        - name: gluster-dev
          hostPath:
            path: "/dev"
        - name: varlog
          emptyDir: {}
        - name: csi-dir
          hostPath:
            path: {{ include "common.configs.kubeletDir" . }}/plugins/kubernetes.io/csi/
            type: DirectoryOrCreate
        - name: kadalu-storagevol
          hostPath:
            path: /mnt/cw_glusterfs/kadalu
        - name: glusterfs-vol
          hostPath: 
            path: /var/run/vmexec-socket/
