apiVersion: v2
name: common
icon: https://kadalu.io/static/css/logo.png
description: kdalu.io Common Chart
type: library
# Value of 'version' will be replaced with correct version on part of release
version: 1.0.0
